spring:
  application:
    name: oauth2
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth2
    username: nttruong
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@email.com
    password: "app password"
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
server:
  port: 9000
logging:
  level:
    org.springframework.security: trace
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace